# Generated by Django 5.2.15 on 2026-06-06 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.ImageField(upload_to='lesson_thumbnails/')),
                ('video_file', models.FileField(upload_to='lesson_videos/')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('letter', models.CharField(blank=True, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_lessons', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='lessons', to='base.lessoncategory')),
            ],
        ),
    ]
