# Generated by Django 5.2.15 on 2026-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
