# Generated by Django 5.2.15 on 2026-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_quizmodule_question_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodule',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_thumbnails/'),
        ),
    ]
