# Generated by Django 5.2.15 on 2026-06-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_quizmodule_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sign_image_url',
        ),
        migrations.AddField(
            model_name='question',
            name='sign_video',
            field=models.FileField(default='', help_text='Upload a video/GIF file showing the ASL sign', upload_to='quiz_videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizmodule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='base.lessoncategory'),
        ),
    ]
