# Generated by Django 5.2.15 on 2026-06-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_communitypost_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
